extraction:
  cpp:
    after_prepare: 
      - python report.py 113
  cobol:
    after_prepare: 
      - python report.py 113
  csharp:
    after_prepare: 
      - python report.py 113
  java:
    after_prepare: 
      - python report.py 113
  javascript:
    after_prepare: 
      - python report.py 113
  python:
    after_prepare: 
      - python report.py 113
